# fly.toml app configuration file generated for ebimex-service-page on 2023-11-07T21:28:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ebimex-service-page"
primary_region = "waw"

[build]
  image = "linky141/ebimexpage:latest"

[env]
  ASPNETCORE_URLS = "http://+:8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
